name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove large files (optional)
        run: |
          git rm -rf --cached "Rag_Documents/layout-parser-paper.pdf" || true
          git commit -m "Remove large file" || true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://srinivasaguru:${HF_TOKEN}@huggingface.co/spaces/srinivasaguru/agenticai
          git push --force origin main
