name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Remove large file before pushing
        run: |
          git rm --cached Rag_Documents/layout-parser-paper.pdf || true
          git commit -m "Remove large file before syncing" || echo "Nothing to commit"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://srinivasaguru:${HF_TOKEN}@huggingface.co/spaces/srinivasaguru/agenticai
          git push --force origin main