name: Sync to Hugging Face Space

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub code
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.name "srinivasaguru1"
          git config --global user.email "srinivasaguru301@gmail.com"

      - name: Push to Hugging Face Space
        run: |
          git clone https://srinivasaguru:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/srinivasaguru/agenticai hf_space
          rsync -av --exclude='.git' ./ hf_space/
          cd hf_space
          git add .
          git commit -m "🚀 Auto-deploy from GitHub Actions" || echo "Nothing to commit"
          git push
